name: Nucleus
main: net.aerulion.nucleus.Main
version: ${project.version}+${buildNumber}
author: aerulion
api-version: '1.17'
libraries:
  - com.zaxxer:HikariCP:4.0.3
commands:
  nucleus:
    description: Core command.